---
- hosts: routers
  gather_facts: false
  host_key_checking : False
  
  tasks:
   - name: run show version on ios device
     cisco.ios.ios_command:
       commands:
         - show ip int br
     register: result

   - debug:
       msg: "{{ result.stdout_lines[0] }}"
     when: result.stdout[0] != ""
