---
- hosts: routers
  gather_facts: false
  
  
  tasks:
   - name: run show version on ios device
     cisco.ios.ios_command:
       commands:
         - show ip int br
     register: result

   - debug:
       msg: "{{ result.stdout_lines[0] }}"
     when: result.stdout[0] != ""
     
   - name: save output to local directory
     copy:
         content: "{{ result.stdout | replace('\\n', '\n') }}"           
         dest: "{{ inventory_hostname }}.ios"
